name: dart_terraform_triggers_workspace
description: "Workspace root for the Dart Terraform Triggers (dtt) toolchain and library ecosystem."
publish_to: none

environment:
  sdk: ^3.12.0

workspace:
  - _integration_test
  - examples/firebase_auth_example
  - packages/dtt
  - packages/dtt_runtime
  - packages/google_cloud_events

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
