// Generated by tool/generate_catalog.dart. Do not edit.

/// High-fidelity, strongly-typed Google CloudEvents schemas and routing
/// catalogs library.
library;

export 'google/events/cloud/audit/v1/data.pb.dart';
export 'google/events/cloud/cloudbuild/v1/data.pb.dart';
export 'google/events/cloud/pubsub/v1/data.pb.dart';
export 'google/events/cloud/storage/v1/data.pb.dart';
export 'google/events/firebase/auth/v1/data.pb.dart';
export 'google/events/firebase/firebasealerts/v1/data.pb.dart';
export 'google/events/firebase/remoteconfig/v1/data.pb.dart';
export 'google_cloud_triggers.dart';
