// Generated by tool/generate_catalog.dart. Do not edit.
import 'package:protobuf/protobuf.dart';
import 'package:protobuf/well_known_types/google/protobuf/struct.pb.dart';

import 'google/events/cloud/storage/v1/data.pb.dart';
import 'google/events/firebase/auth/v1/data.pb.dart';

/// Centralized, strongly-typed Enum catalog resolving GCP and Firebase
/// triggers.
/// Conforms to official Eventarc and CloudEvents specifications.
enum CloudEventTrigger<T extends GeneratedMessage> {
  /// Triggered on event: google.cloud.firestore.document.v1.created
  firestoreDocumentCreated<Struct>(
    eventType: 'google.cloud.firestore.document.v1.created',
    defaultPath: '/events/firestore/created',
    create: Struct.create,
  ),

  /// Triggered on event: google.cloud.firestore.document.v1.deleted
  firestoreDocumentDeleted<Struct>(
    eventType: 'google.cloud.firestore.document.v1.deleted',
    defaultPath: '/events/firestore/deleted',
    create: Struct.create,
  ),

  /// Triggered on event: google.cloud.firestore.document.v1.updated
  firestoreDocumentUpdated<Struct>(
    eventType: 'google.cloud.firestore.document.v1.updated',
    defaultPath: '/events/firestore/updated',
    create: Struct.create,
  ),

  /// Triggered on event: google.cloud.firestore.document.v1.written
  firestoreDocumentWritten<Struct>(
    eventType: 'google.cloud.firestore.document.v1.written',
    defaultPath: '/events/firestore',
    create: Struct.create,
  ),

  /// Triggered on event: google.cloud.storage.object.v1.archived
  gcsObjectArchived<StorageObjectData>(
    eventType: 'google.cloud.storage.object.v1.archived',
    defaultPath: '/events/uploads/archived',
    create: StorageObjectData.create,
  ),

  /// Triggered on event: google.cloud.storage.object.v1.deleted
  gcsObjectDeleted<StorageObjectData>(
    eventType: 'google.cloud.storage.object.v1.deleted',
    defaultPath: '/events/uploads/deleted',
    create: StorageObjectData.create,
  ),

  /// Triggered on event: google.cloud.storage.object.v1.finalized
  gcsObjectFinalized<StorageObjectData>(
    eventType: 'google.cloud.storage.object.v1.finalized',
    defaultPath: '/events/uploads',
    create: StorageObjectData.create,
  ),

  /// Triggered on event: google.cloud.storage.object.v1.metadataUpdated
  gcsObjectMetadataUpdated<StorageObjectData>(
    eventType: 'google.cloud.storage.object.v1.metadataUpdated',
    defaultPath: '/events/uploads/metadata',
    create: StorageObjectData.create,
  ),

  /// Triggered on event: google.firebase.auth.user.v2.created
  firebaseAuthUserCreated<AuthEventData>(
    eventType: 'google.firebase.auth.user.v2.created',
    defaultPath: '/events/auth',
    create: AuthEventData.create,
  ),

  /// Triggered on event: google.firebase.auth.user.v2.deleted
  firebaseAuthUserDeleted<AuthEventData>(
    eventType: 'google.firebase.auth.user.v2.deleted',
    defaultPath: '/events/auth/deleted',
    create: AuthEventData.create,
  );

  /// Unique Eventarc GCP/Firebase trigger event type.
  final String eventType;

  /// Default HTTP webhook request endpoint path route.
  final String defaultPath;

  /// Target Protobuf constructor factory template creator.
  final T Function() create;

  const CloudEventTrigger({
    required this.eventType,
    required this.defaultPath,
    required this.create,
  });
}
