// Copyright 2026 Google LLC

// ignore_for_file: unreachable_from_main

import 'dart:io';

final class ServiceFamily {
  final String enumPrefix;
  final String protoClass;
  final String eventsImport;
  final String dttImport;
  final String basePath;
  final String baselineAction;
  final bool isGlobal;
  final String? triggerLocation;
  final String? contentType;

  const ServiceFamily({
    required this.enumPrefix,
    required this.protoClass,
    required this.eventsImport,
    required this.dttImport,
    required this.basePath,
    required this.baselineAction,
    this.isGlobal = false,
    this.triggerLocation,
    this.contentType,
  });
}

const families = {
  'google.cloud.storage': ServiceFamily(
    enumPrefix: 'gcsObject',
    protoClass: 'StorageObjectData',
    eventsImport: 'google/events/cloud/storage/v1/data.pb.dart',
    dttImport:
        'package:google_cloud_events/google/events/'
        'cloud/storage/v1/data.pb.dart',
    basePath: '/events/uploads',
    baselineAction: 'finalized',
  ),
  'google.cloud.firestore': ServiceFamily(
    enumPrefix: 'firestoreDocument',
    protoClass: 'Struct',
    eventsImport:
        'package:protobuf/well_known_types/google/protobuf/'
        'struct.pb.dart',
    dttImport:
        'package:protobuf/well_known_types/google/protobuf/'
        'struct.pb.dart',
    basePath: '/events/firestore',
    baselineAction: 'written',
    triggerLocation: 'nam5',
    contentType: 'application/protobuf',
  ),
  'google.firebase.auth': ServiceFamily(
    enumPrefix: 'firebaseAuthUser',
    protoClass: 'AuthEventData',
    eventsImport: 'google/events/firebase/auth/v1/data.pb.dart',
    dttImport:
        'package:google_cloud_events/google/events/'
        'firebase/auth/v1/data.pb.dart',
    basePath: '/events/auth',
    baselineAction: 'created',
    isGlobal: true,
    triggerLocation: 'global',
  ),
};

String _capitalize(String s) =>
    s.isEmpty ? s : s[0].toUpperCase() + s.substring(1);

Future<void> main() async {
  final inputFile = File('catalog/supported_triggers.txt');
  if (!inputFile.existsSync()) {
    stderr.writeln('Missing catalog/supported_triggers.txt');
    exitCode = 1;
    return;
  }

  final lines =
      inputFile
          .readAsLinesSync()
          .map((l) => l.trim())
          .where((l) => l.isNotEmpty && !l.startsWith('#'))
          .toList()
        ..sort();

  final eventsEntries = <String>[];
  final dttEntries = <String>[];

  for (final line in lines) {
    ServiceFamily? fam;
    String? serviceKey;
    for (final key in families.keys) {
      if (line.startsWith(key)) {
        fam = families[key];
        serviceKey = key;
        break;
      }
    }
    if (fam == null || serviceKey == null) {
      throw FormatException('Unregistered service prefix in line: $line');
    }

    final parts = line.split('.');
    final action = parts.last;
    final camelName = fam.enumPrefix + _capitalize(action);
    final pathSuffix = action == fam.baselineAction
        ? ''
        : '/${action == 'metadataUpdated' ? 'metadata' : action}';
    final routePath = fam.basePath + pathSuffix;

    eventsEntries.add('''
  /// Triggered on event: $line
  $camelName<${fam.protoClass}>(
    eventType: '$line',
    defaultPath: '$routePath',
    create: ${fam.protoClass}.create,
  )''');

    final metaArgs = <String>[
      "importPath: '${fam.dttImport}'",
      "className: '${fam.protoClass}'",
      "enumName: 'CloudEventTrigger.$camelName'",
      "defaultPath: '$routePath'",
      if (fam.isGlobal) 'isGlobal: true',
      if (fam.triggerLocation != null)
        "triggerLocation: '${fam.triggerLocation}'",
      if (fam.contentType != null) "eventDataContentType: '${fam.contentType}'",
    ];

    dttEntries.add('''
  $camelName(
    identifier: '$line',
    meta: TriggerTypeMeta._(
${metaArgs.map((a) => '      $a,').join('\n')}
    ),
  )''');
  }

  final eventsFile = File(
    'packages/google_cloud_events/lib/google_cloud_triggers.dart',
  );
  await eventsFile.writeAsString('''
// Generated by tool/generate_catalog.dart. Do not edit.
import 'package:protobuf/protobuf.dart';
import 'package:protobuf/well_known_types/google/protobuf/struct.pb.dart';

import 'google/events/cloud/storage/v1/data.pb.dart';
import 'google/events/firebase/auth/v1/data.pb.dart';

/// Centralized, strongly-typed Enum catalog resolving GCP and Firebase
/// triggers.
/// Conforms to official Eventarc and CloudEvents specifications.
enum CloudEventTrigger<T extends GeneratedMessage> {
${eventsEntries.join(',\n')};

  /// Unique Eventarc GCP/Firebase trigger event type.
  final String eventType;

  /// Default HTTP webhook request endpoint path route.
  final String defaultPath;

  /// Target Protobuf constructor factory template creator.
  final T Function() create;

  const CloudEventTrigger({
    required this.eventType,
    required this.defaultPath,
    required this.create,
  });
}
''');

  final dttFile = File('packages/dtt/lib/src/codegen/trigger_config.g.dart');
  await dttFile.writeAsString('''
// Generated by tool/generate_catalog.dart. Do not edit.
part of 'trigger_config.dart';

/// Supported Eventarc trigger event types and their associated schema metadata.
enum TriggerType {
${dttEntries.join(',\n')};

  const TriggerType({required this.identifier, required this.meta});

  final String identifier;
  final TriggerTypeMeta meta;

  static TriggerType fromIdentifier(String id) {
    for (final val in values) {
      if (val.identifier == id) return val;
    }
    throw UnsupportedError(
      'Target Eventarc trigger type [\$id] is not registered in schemas '
      'catalog.',
    );
  }
}
''');

  print('📦 Running dart format...');
  await Process.run('dart', ['format', eventsFile.path, dttFile.path]);
  print('✅ Catalogs generated successfully!');
}
