name: option_1_functions_framework
description: "Option 1: Deploying Dart events built on top of standard Google functions-framework-dart."
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  functions_framework:
  protobuf:
  shelf:

dev_dependencies:
  build_runner:
  functions_framework_builder:
